routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('reserves');
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/hall', 'HallController@hall')->name('hall');
Route::resource('/movies', 'MovieController');
Route::get('/movie', 'MovieController@singlePage')->name('movie.show');
Route::get('/test', 'MovieController@index');
Route::get('/categories', 'CategoryController@index')->name('page');
Route::post('/categories', 'CategoryController@store')->name('category.store');
Route::resource('/admin', 'AdminController');
Route::resource('/reserves', 'ReserveController');

resources/views/blue.blade.php
<h1>Blue</h1>

resources/views/category.blade.php
@extends('layouts.app')
@section('content')
    <form method="POST" action="{{ route('category.store') }}" class="col-md-5 mx-auto mt-5" id="product_form" enctype="multipart/form-data">
        @csrf
        <div class="form-group row">
            <label for="name" class="col-md-3 col-form-label text-md-right">{{ __('genre') }}</label>
            <div class="col-md-6">
                <input id="name" type="text" class="form-control" name="name" autofocus>
                <span role="alert">
                        <strong class="errors"></strong>
                    </span>
            </div>
        </div>
        <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-3">
                <button type="submit" class="btn btn-primary">
                    {{ __('Save') }}
                </button>
            </div>
        </div>
    </form>
@endsection

resources/views/green.blade.php
<h1>Green</h1>

resources/views/home.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="main">
                <h1 class="cinema">Cinema Mgoongie</h1>
                <h2 class="halls">Halls</h2>
                <div class="row">
                    @foreach($halls as $hall)
                    <a class="item col-md-4" href="{{route('hall', ['hall' => 'red', 'id' => $hall->id])}}">
                        <p class="item_description">{{$hall->type}}</p>
                        <div class="image"
                             style="background-image: url({{$hall->bg_image}}); border-radius: 50%; background-color: {{$hall->color}}"></div>
                    </a>
                    @endforeach
                </div>
            </div>

        </div>
    </div>
@endsection

resources/views/movie-card.blade.php
@extends('layouts.app')
@section('content')
    {{--    @php dd($movie) @endphp--}}
    <div class="container">
        <div class="row">
            <div class="movie_card" id="ave">
                <div class="info_section">
                    <div class="movie_header">
                        <img class="locandina" src="{{$files->first()->name}}"/>
                        <h1 class="header">{{$movie->film_name}}</h1>

                    </div>
                    <div class="movie_desc">
                        <h4 class="header">{{$movie->director}}</h4>
                        <p class="text"> {{$movie->description}}</p>
                        <span class="minutes">{{$movie->duration}}</span>
                        <p class="type"> {{$movie->genre}}</p>
                    </div>
                    <div class="movie_social">
                        <ul>
                            <li><i class="fa fa-share"></i></li>
                            <li><i class="fa fa-heart"></i></li>
                            <li><i class="fa fa-comment"></i></li>
                            <li><a class="btn btn-success" href="{{route('reserves.index', [ 'movie' => $movie->id])}}">
                                    {{ __('Reserve a
                                        seat') }}
                                </a></li>
                        </ul>
                    </div>
                </div>
                <div class="blur_back ave_back" style="background: url('{{$files->last()->name}}')"></div>
            </div>
        </div>
    </div>
@endsection

resources/views/movie.blade.php
@extends('layouts.app')
@section('content')
    <form method="POST" action="{{ route('movies.store') }}" class="col-md-5 mx-auto mt-5" id="product_form"
          enctype="multipart/form-data">
        @csrf
        <div class="form-group row">
            <label for="name" class="col-md-3 col-form-label text-md-right">{{ __('Name') }}</label>
            <div class="col-md-6">
                <input id="name" type="text" class="form-control" name="name" autofocus>
                <span role="alert">
                        <strong class="errors"></strong>
                    </span>
            </div>
        </div>
        <div class="form-group row">
            <label for="description" class="col-md-3 col-form-label text-md-right">{{ __('Description') }}</label>
            <div class="col-md-6">
                <input id="description" type="text" class="form-control" name="description">
                <span role="alert">
                        <strong class="errors"></strong>
                    </span>
            </div>
        </div>
        <div class="form-group row">
            <label for="time" class="col-md-3 col-form-label text-md-right">{{ __('Duration (minutes)') }}</label>
            <div class="col-md-6">
                <input id="time" type="number" class="form-control"
                       name="duration">
                <span role="alert">
                        <strong class="errors"></strong>
                    </span>
            </div>
        </div>
        <div class="form-group row">
            <label for="category" class="col-md-3 col-form-label text-md-right">{{ __('Genre') }}</label>
            <div class="col-md-6">
                <div class="col-md-4">
                    @foreach($categories as $category)
                        <div class="round">
                            <input type="checkbox" id="cat{{$category->id}}" name="categories[]"
                                   value="{{$category->id}}">
                            <label for="cat{{$category->id}}">
                                {{ $category->genre }}
                            </label>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
        <div class="form-group row">
            <label for="start" class="col-md-3 col-form-label text-md-right">{{ __('Start time') }}</label>
            <div class="col-md-6">
                <div class="input-group clockpicker" data-placement="right" data-align="top" data-autoclose="true">
                    <input type="text" class="form-control" name="time" id="start">
                    <span class="input-group-addon">
		        <span class="glyphicon glyphicon-time"></span>
	        </span>
                </div>
            </div>
        </div>
        <div class="form-group row">
            <label for="date" class="col-md-3 col-form-label text-md-right">{{ __('Date') }}</label>
            <div class="col-md-6">
                    <input type="date" class="form-control" name="date" id="date">
            </div>
        </div>
        <div class="form-group row">
            <label for="director" class="col-md-3 col-form-label text-md-right">{{ __('Director') }}</label>
            <div class="col-md-6">
                <input id="director" type="text" class="form-control"
                       name="director">
                <span role="alert">
                        <strong class="errors"></strong>
                    </span>
            </div>
        </div>
        <div class="form-group row">
            <label for="halls" class="col-md-3 col-form-label text-md-right">{{__('Hall')}}</label>
            <div class="col-md-6">
                <select name="hall" id="halls" class="form-control">
                    @foreach($halls as $hall)
                        <option value="{{$hall->id}}"> {{ $hall->type }}</option>
                    @endforeach
                </select>
                <span role="alert">
                        <strong class="errors"></strong>
                    </span>
            </div>
        </div>
        <div class="form-group row">
            <label for="upload" class="col-md-3 col-form-label text-md-right">{{ __('Upload') }}</label>
            <div class="col-md-6">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroupFileAddon01">Upload</span>
                    </div>
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="inputGroupFile01"
                               aria-describedby="inputGroupFileAddon01" name="files[]" multiple>
                        <span></span>
                        <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
                        <span></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-3">
                <button type="submit" class="btn btn-primary">
                    {{ __('Save') }}
                </button>
            </div>
        </div>
    </form>

@endsection

resources/views/movies-table.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <table class="table">
                <thead class="bg-warning">
                <tr>
                    {{--<th scope="col">Id</th>--}}
                    <th scope="col">Name</th>
                    <th scope="col">Description</th>
                    <th scope="col">Duration</th>
                    <th scope="col">Director</th>
                    <th scope="col">Genres</th>
                    <th scope="col">Date</th>
                    <th scope="col">Start time</th>
                    <th scope="col">Edit</th>
                    <th scope="col">Delete</th>
                </tr>
                </thead>
                <tbody>
                @foreach($allMovies as $movie)
                    <tr>
                        {{--<td>{{$movie->id}}</td>--}}
                    <td><a href="{{route('movie.show', [ 'movie_id' => $movie->id ])}}">{{$movie->name}}</a></td>
                        <td>{{$movie->description}}</td>
                        <td>{{$movie->duration}}</td>
                        <td>{{$movie->director}}</td>
                        <td>{{$movie->genre}}</td>
                        <td>{{$movie->date}}</td>
                        <td>{{$movie->start_time}}</td>
                        <td>
                            <button class="btn btn-success">Edit</button>
                        </td>
                        <td>
                            <button class="btn btn-danger">Delete</button>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/red.blade.php
@extends('layouts.app')
@section('content')
    @foreach($movies as $movie)
    <div class="movie_card" id="ave">
        <div class="info_section">
            <div class="movie_header">
                <img class="locandina" src="{{$movie->name}}"/>
                <h1>{{$movie->f_name}}</h1>
                <h4>{{$movie->director}}</h4>
                <span class="minutes">{{$movie->duration}}</span>
                <p class="type">{{$movie->genre}}</p>
            </div>
            <div class="movie_desc">
                <p class="text">
                    {{$movie->description}}
                </p>
            </div>
            <div class="movie_social">
                <ul>
                    <li><i class="fa fa-share"></i></li>
                    <li><i class="fa fa-heart"></i></li>
                    <li><i class="fa fa-comment"></i></li>
                </ul>
            </div>
        </div>
        <div class="blur_back ave_back"></div>
    </div>
    @endforeach
@endsection

resources/views/reserves.blade.php
@extends('layouts.app')
@section('content')
    <form method="post" action="{{route('reserves.store')}}">
        @csrf
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <h1>Reserve your seat</h1>
                </div>
                <div class="uk-margin uk-grid-small uk-child-width-auto uk-grid w-25">
                    @for($i=1; $i <=81; $i++)
                        <label><input class="uk-checkbox" type="checkbox" id="{{$i}}" name="seat[]"
                                      value="{{$i}}"></label>
                    @endfor
                    @foreach($movies as $movie)
                        <input type="hidden" value="{{$movie->id}}" name="id">
                    @endforeach
                    <button type="submit" class="btn btn-success"> Save</button>
                </div>
            </div>
        </div>
    </form>
    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif
@endsection

resources/views/test.blade.php
@php